[log]
  level = "ERROR"

#[accessLog]
  
#[serversTransport]
#  insecureSkipVerify = true

[entryPoints]
  [entryPoints.websecure]
    address = ":443"
	  [entryPoints.websecure.http.tls]
	[entryPoints.websecure.http]
	  middlewares = ["whitelist@file", "headers@file"]
    
[api]
  dashboard = true

[providers]
  [providers.docker]
	exposedByDefault = false
  [providers.file]
    directory = "/dynamicconf"
    watch = true